name: "Java CI with Gradle"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: "Set up JDK"
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2

      - name: "Gradle build"
        run: ./gradlew build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

        # "Make sure the `assemble` task is executed."
        # - https://docs.sentry.io/platforms/java/source-context/
      - name: "Gradle assemble"
        run: ./gradlew assemble
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: "Generate Kover report"
        run: ./gradlew koverXmlReport

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
