name: "Java CI with Gradle"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: "Set up JDK"
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@a8f75513eafdebd8141bd1cd4e30fcd194af8dfa # v2.12.0

      - name: "Gradle build"
        run: ./gradlew build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

        # "Make sure the `assemble` task is executed."
        # - https://docs.sentry.io/platforms/java/source-context/
      - name: "Gradle assemble"
        run: ./gradlew assemble
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: "Generate Kover report"
        run: ./gradlew koverXmlReport

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@4fe8c5f003fae66aa5ebb77cfd3e7bfbbda0b6b0 # v3.1.5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
