name: "Java CI with Gradle"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: "Set up JDK"
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: "Gradle build"
        run: ./gradlew build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

        # "Make sure the `assemble` task is executed."
        # - https://docs.sentry.io/platforms/java/source-context/
      - name: "Gradle assemble"
        run: ./gradlew assemble
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: "Generate Kover report"
        run: ./gradlew koverXmlReport

      - name: "Upload coverage reports to Codecov"
        uses: codecov/codecov-action@c16abc29c95fcf9174b58eb7e1abf4c866893bc8 # v4.1.1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
